fragment CalendarMatch on Match {
    slug
    matchDate: match_date
    hasOdds: has_odds
    hasPrediction: has_prediction
    resultScore: result_score
    minute
    hasStandings: has_standings
    hasH2h: has_h2h
    isLive: is_live
    status {
        code
    }
    cards {
        color
        team
    }
    resultScores: result_scores {
        type
        value
    }
    isFinished: is_finished
    winner
    teams {
        name
        logo
        slug
        country {
            iso
        }
    }
}
